version: '3.8'

services:
  traefik:
    image: traefik:v2.10
    container_name: traefik
    command:
      - "--api.insecure=true"  # Bật dashboard (tuỳ chọn)
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"  # Traefik dashboard (có thể bỏ nếu không cần)
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - mt5-network

  mt5app:
    image: gmag11/metatrader5_vnc
    container_name: mt5app
    environment:
      - CUSTOM_USER=bigdata # VNC
      - PASSWORD=bigdata # VNC
    volumes:
      - ./config:/config
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mt5app.rule=Host(`mt5.yourdomain.com`)"
      - "traefik.http.routers.mt5app.entrypoints=web"
      - "traefik.http.services.mt5app.loadbalancer.server.port=3000"
    restart: unless-stopped
    networks:
      - mt5-network

  mt5pull:
    build:
      context: ./pull
      dockerfile: Dockerfile
    container_name: mt5pull
    environment:
      - MT5_HOST=mt5app
      - MT5_PORT=8001
      - DB_LOCAL_URL=postgresql+psycopg2://admin:1234@188.172.228.17:5432/dapp_local_data
    ports:
      - 4000:4000
    links:
      - "mt5app:mt5app"
    networks:
      - mt5-network
    restart: unless-stopped

networks:
  mt5-network:
    driver: bridge
